# Generated by Django 5.1.2 on 2024-10-10 08:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('brand_img', models.ImageField(blank=True, null=True, upload_to='brand')),
                ('brand_name', models.CharField(max_length=50, unique=True)),
                ('brand_description', models.TextField()),
            ],
        ),
    ]
