# Generated by Django 5.1.2 on 2024-10-10 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('min_amount', models.PositiveBigIntegerField(default=15000)),
                ('discount_price', models.PositiveBigIntegerField(default=799)),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='variant_thumbnail')),
                ('quantity', models.PositiveIntegerField(blank=True)),
                ('price', models.PositiveIntegerField(null=True)),
                ('is_available', models.BooleanField(blank=True, default=True)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_variant.colors')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Variant_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='variant_images')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='admin_variant.product_variant')),
            ],
        ),
    ]
